source 'https://rubygems.org'

gemspec

# Add debugger for pry that's compatible with 0.10.4
gem 'pry-nav', git: 'https://github.com/nixme/pry-nav.git', branch: 'master'
# This file was generated by Appraisal

gem 'activerecord'
gem 'rack-test'
gem 'sinatra', '~> 2'
gem 'sqlite3', '~> 1.4'
